### ISSUE TITLE
您好，请教一下标签表征和代码中masking相关问题。

### ISSUE THREAD

**Issue by 1535966643** [Nealcly/LAN#18]
1.其中的label representation，是指对所有标签做embedding然后和biLSTM的embedding做attention吗
2.论文中并没有将mask，但是代码中attention有mask，没看懂
请教您，谢谢谢谢

**Comment by Nealcly** [comment]
1.对的
2.只对词序列进行了mask

**Comment by 1535966643** [comment]
1为什么要进行mask？论文似乎没有提到呀！
2论文的实现思路，BiLSTM的embedding和label embedding做attention，然后再将attention和BiLSTM做连接，连接内容作为输入再次进入下层BiLSTM是这样吗？我直接这么去实现，是否能复现结果？
再次麻烦您了

**Comment by Nealcly** [comment]
1. 因为有pad，所以要对词序列mask
2.对的

**Comment by 1535966643** [comment]
谢谢你
