### ISSUE TITLE
Question about dataset splitting

### ISSUE THREAD

**Issue by speedcell4** [Nealcly/LAN#2]
Hi~

How did you split your OntoNotes datasets into train/dev/test? 
I found a script (https://github.com/yuchenlin/OntoNotes-5.0-NER-BIO), but the number of sentences in the results is different from Table 1 in your paper.
Could you please show me how did you split them?

**Comment by Nealcly** [comment]
Hi,

https://github.com/allanj/pytorch_lstmcrf/blob/master/docs/benchmark.md
I hope this could help you. If you have any further questions, please email me directly.

**Comment by speedcell4** [comment]
> and use the test split with the preprocessing scripts from http://cemantix.org/data/ontonotes.html

but the preprocessing scripts are not available on that page
