### ISSUE TITLE
Can you provide the pre-trained model ?

### ISSUE THREAD

**Issue by KelleyYin** [Nealcly/LAN#3]
It's a very wonderful work. 
Can you provide the pre-trained model ? I want to use it to decode text directly.

Thanks.

**Comment by Nealcly** [comment]
May I ask which model do you want to use? I will upload it as soon as possible.

**Comment by KelleyYin** [comment]
@Nealcly Thank you for your reply.

The method you proposed can effectively improve the accuracy in task of POS tagging. 
I want to use this model to decode my own text data.

**Comment by Nealcly** [comment]
Please find the link below to download
https://drive.google.com/open?id=1C2VezGZJqw7IxmPslQbwlawYzL__NYwS
I will update readme later.

**Comment by KelleyYin** [comment]
Thank you very much.
Do you give a script about decoding command ?
